### PR TITLE
Dart 2.19.0 linter fixes

### LINKED ISSUE #164: Fix Dart 2.19 linter issues
Dart 2.19 is out, it added issues.

### PR DESCRIPTION
**Pull request by yescorp**
- Resolves #164

### CODE REVIEW

File: test/src/code_field/code_controller_readonly_test.dart [hunk 1]
```diff
@@ -197,7 +197,10 @@ void main() {
           const TextEditingValue(
             text: 'abc\nro\nro\nabc\n',
             //        \ cursor
-            selection: TextSelection.collapsed(offset: 3),
+            selection: TextSelection.collapsed(
+              offset: 3,
+              affinity: TextAffinity.upstream,
+            ),
```
Comment (yescorp) [inline test/src/code_field/code_controller_readonly_test.dart:203]: This test is failing because of the new version :/
For now I changed affinity to be as the actual result.

Still trying to find the reason.

**Comment by alexeyinkin** [comment]
I filed a Flutter issue:
- https://github.com/flutter/flutter/issues/119933

Given that you can:
1. Comment out that failing expectation.
2. File a new issue to get it back, add a TODO there.
3. Link to the Flutter issue in our new issue.
4. Proceed with this PR.

By the way, you can use 3.7.1 now in the workflow.

**Review by alexeyinkin — APPROVED** [review]
