### PR TITLE
issue 242 fixed bug: Search selection jumped when change search pattern that also fit to current selection

### LINKED ISSUE #242: Search selection jumps when change search pattern that also fit to current selection

### PR DESCRIPTION
**Pull request by Malarg**
- Resolves #242

issue 242 fixed bug: Search selection jumped when change search pattern that also fit to current selection

### CODE REVIEW

File: lib/src/search/search_navigation_controller.dart [hunk 1]
```diff
@@ -104,14 +104,16 @@ class SearchNavigationController extends ValueNotifier<SearchNavigationState> {
...
+    final fullSelectionStart = codeController.code.hiddenRanges.recoverPosition(
+      visibleSelectionStart,
       placeHiddenRanges: TextAffinity.downstream,
     );
 
     var closestMatchIndex = _lastFullSearchResult.matches.indexWhere(
-      (element) => element.start >= fullSelectionEnd,
+      (element) {
+        return element.start >= fullSelectionStart;
+      },
```
Comment (alexeyinkin) [inline lib/src/search/search_navigation_controller.dart:116]: Back to lambda?

File: test/src/search/search_navigation_test.dart [hunk 2]
```diff
@@ -262,6 +262,41 @@ d
         null,
       );
     });
+
+    testWidgets('Changing search pattern with match at current '
+    'selection will not jump to next', (wt) async {
```
Comment (alexeyinkin) [inline test/src/search/search_navigation_test.dart:267]: If you are testing that something is NOT happening, put the test to `issues` directory. Because most of the things the world can do to us do NOT happen, and it is unclear why we should test this one.

If keeping the test here, name it after what SHOULD happen.

File: lib/src/code_field/search_result_highlighted_builder.dart [hunk 3]
```diff
@@ -4,7 +4,7 @@ import '../search/result.dart';
 import '../search/search_navigation_state.dart';
 
 @visibleForTesting
-const matchBackgroundColor = Color.fromARGB(141, 255, 235, 59);
+const matchBackgroundColor = Colors.green;
```
Comment (alexeyinkin) [inline lib/src/code_field/search_result_highlighted_builder.dart:7]: Let's use Chrome's colors instead as it is the most popular browser, and the people are used to it.
image

**Review by alexeyinkin — APPROVED** [review]
