### PR TITLE
Get edit result fix

### LINKED ISSUE #210: Backspace on the line before a folded block deletes the folded code
https://user-images.githubusercontent.com/44893228/231163449-8141ae35-0257-40f6-8786-9d95758c5e18.mp4

### PR DESCRIPTION
**Pull request by yescorp**
- Resolves #210

### CODE REVIEW

File: test/src/code_field/code_controller_set_value_test.dart [hunk 1]
```diff
@@ -0,0 +1,64 @@
+import 'package:flutter/services.dart';
+import 'package:flutter_test/flutter_test.dart';
+
+import '../common/create_app.dart';
+
+void main() {
+  testWidgets(
+      'Backspace or delete through folded block '
```
Comment (alexeyinkin) [inline test/src/code_field/code_controller_set_value_test.dart:8]:
```suggestion
      'Backspace or delete at a folded block collapse point '
```

File: test/src/code_field/code_controller_set_value_test.dart [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+      '=> Do nothing.', (wt) async {
+    final examples = [
+      //
+      const _Example(
+        'Backspace right after folded block',
```
Comment (alexeyinkin) [inline test/src/code_field/code_controller_set_value_test.dart:13]:
```suggestion
        'Backspace after newline after folded block',
```

File: lib/src/code_field/text_editing_value.dart [hunk 3]
```diff
@@ -185,4 +185,28 @@ extension TextEditingValueExtension on TextEditingValue {
       text: text,
     );
   }
+
+  /// Checks if the newValue is most likely caused by the `delete` button.
+  bool isDelete(TextEditingValue newValue) {
```
Comment (alexeyinkin) [inline lib/src/code_field/text_editing_value.dart:190]: Make this a method on the new value.
```suggestion
  /// Checks if this could be produced by pressing delete on the [oldValue].
  bool wasDeletePressedOn(TextEditingValue oldValue) {
```

**Review by alexeyinkin — APPROVED** [review]
