### PR TITLE
History controller refactored

### LINKED ISSUE #132: Undo sets the cursor to the beginning of the document
https://user-images.githubusercontent.com/44893228/210773697-c867e1ed-88b4-4a3d-892d-1698a1526fcc.mp4

### LINKED ISSUE #186: Undo action issue
Undo action works incorrect: In this example after one undo action 2 actions happened: delete typed text and recover deleted
https://user-images.githubusercontent.com/17158960/218919532-b94ff00d-c74e-443e-9131-899dbd785764.mov

### LINKED ISSUE #193: For discussion: History controller interaction with folding
Seems like right now history controller snapshots the folding state of code as well.

https://user-images.githubusercontent.com/79095619/219439576-62ef5bc3-3acb-49f8-a08a-61ca9622c1ac.mov

IMO it is not practical at all. if the text inside folded block is not affected by it.

### PR DESCRIPTION
**Pull request by yescorp**
- Resolves #132 
- Resolves #186 
- Resolves #193

### CODE REVIEW

File: lib/src/history/code_history_controller.dart [hunk 1]
```diff
@@ -46,45 +52,109 @@ class CodeHistoryController {
...
+
+    _removeLastRedundantSelectionOnlyChanges();
+  }
+
+  HistoryControllerAction _getAction({
+    required Code code,
+    required TextSelection selection,
+    required bool isTextChanging,
+  }) {
+    {
```
Comment (alexeyinkin) [inline lib/src/history/code_history_controller.dart:95]: Delete redundant braces.

File: lib/src/history/code_history_controller.dart [hunk 2]
```diff
@@ -46,45 +52,109 @@ class CodeHistoryController {
...
+      case 2:
+        // Drop the first one if only selection has changed.
+        if (_isFullTextSame([stack[0], stack[1]])) {
+          stack.removeAt(0);
+        }
+        break;
+
+      default:
+        // Check last, last-1, last-2. Drop last-1.
+        final last = stack.last;
```
Comment (alexeyinkin) [inline lib/src/history/code_history_controller.dart:131]:
```suggestion
        final last = stack[stack.length - 1];
```
?

File: lib/src/history/code_history_controller.dart [hunk 3]
```diff
@@ -46,45 +52,109 @@ class CodeHistoryController {
...
-    lastSelection = selection;
+    return true;
   }
 
   void _dropRedoIfAny() {
-    stack.removeStartingAt(_currentRecordIndex + 1);
+    final startIndexToRemove = _currentRecordIndex + 1;
+    if (startIndexToRemove < stack.length) {
+      stack.removeStartingAt(startIndexToRemove);
+    }
```
Comment (alexeyinkin) [inline lib/src/history/code_history_controller.dart:157]: I cannot imagine an error that would require this. Maybe we need to decrement `_currentRecordIndex` in `_removeLastRedundantSelectionOnlyChanges`?
Otherwise please revert this and find the scenario when this fails, write a test, and then re-apply this.

File: lib/src/history/code_history_controller.dart [hunk 4]
```diff
@@ -115,6 +185,20 @@ class CodeHistoryController {
   }
 
   void _push() {
+    if (!lastSelection.isValid) {
+      // Do not create record for invalid selection
+      // as it is not considered to be standart user input.
+      return;
+    }
```
Comment (alexeyinkin) [inline lib/src/history/code_history_controller.dart:192]: Looks like a disguise for an erroneously losing selection when inserting a suggestion. Please try to preserve selection when inserting it.

File: lib/src/history/code_history_controller.dart [hunk 5]
```diff
@@ -46,45 +52,109 @@ class CodeHistoryController {
...
+
+      default:
+        // Check last, last-1, last-2. Drop last-1.
+        final last = stack.last;
+        final lastMinus1 = stack[stack.length - 2];
+        final lastMinus2 = stack[stack.length - 3];
+
+        if (_isFullTextSame([last, lastMinus1, lastMinus2])) {
+          stack.removeAt(stack.length - 2);
         }
```
Comment (alexeyinkin) [inline lib/src/history/code_history_controller.dart:137]: Also check if `lastMinus2 == lastMinus3`. This happens with multiple `enter` presses. Remove the check from `_push()`.

File: test/src/history/code_history_controller_test.dart [hunk 6]
```diff
@@ -17,14 +17,60 @@ void main() {
...
         final controller = await pumpController(wt, MethodSnippet.full);
 
+        expect(controller.historyController.stack.length, 0);
+      });
+
+      testWidgets('Selection change creates 1 record after change', (wt) async {
+        final controller = await pumpController(wt, MethodSnippet.full);
+
+        // The stack is empty -> Selection change creates.
+        await wt.moveCursor(-1);
```
Comment (alexeyinkin) [inline test/src/history/code_history_controller_test.dart:27]: Write a comment: where is the cursor before this?

**Review by alexeyinkin — CHANGES_REQUESTED** [review]

File: lib/src/history/code_history_controller.dart (hunk 3 above)
Comment (yescorp) [reply lib/src/history/code_history_controller.dart]: Yeah, decrementing fixed it.

File: lib/src/history/code_history_controller.dart (hunk 4 above)
Comment (yescorp) [reply lib/src/history/code_history_controller.dart]: Turns out, the method insertSelectedWord worked in a weird way.

File: test/src/history/code_history_controller_test.dart [hunk 7]
```diff
@@ -252,73 +378,120 @@ void main() {
...
 
         await wt.sendRedo(); // No effect.
+        expect(controller.code.text, code4.text);
+        expect(controller.selection, selection4);
+        expect(controller.historyController.stack.last.code, code2);
+        expect(controller.historyController.stack.last.selection, selection2);
+      });
 
-        expect(controller.historyController.stack.length, 2);
+      testWidgets('Folded blocks match when undo/redo', (wt) async {
```
Comment (alexeyinkin) [inline test/src/history/code_history_controller_test.dart:406]: Start typing -> Fold -> Continue -> Undo -> Still folded

File: test/src/history/code_history_controller_test.dart [hunk 8]
```diff
@@ -252,73 +378,120 @@ void main() {
...
-        expect(controller.historyController.stack.length, 2);
+        expect(controller.historyController.stack.length, 1);
       });
 
       testWidgets('Limit depth', (WidgetTester wt) async {
         final controller = await pumpController(wt, MethodSnippet.full);
         await wt.cursorEnd();
 
         // 1. Fill the limit.
-
```
Comment (alexeyinkin) [inline test/src/history/code_history_controller_test.dart:316]: Keep the blank line because the comment concerns not only the line below.

File: test/src/history/code_history_controller_test.dart [hunk 9]
```diff
@@ -252,73 +378,120 @@ void main() {
...
-        for (int i = 0; i < CodeHistoryController.limit - 1; i++) {
+        for (int i = 0; i < CodeHistoryController.limit / 2 - 1; i++) {
           controller.value = controller.value.typed('a');
           await wt.moveCursor(-1); // Creates.
         }
```
Comment (alexeyinkin) [inline test/src/history/code_history_controller_test.dart:486]: Insert `ab` on each iteration so that it creates exactly 1 record. This way we avoid dependency on `limit` being even.

File: test/src/history/code_history_controller_test.dart [hunk 10]
```diff
@@ -252,73 +378,120 @@ void main() {
...
         await wt.pumpAndSettle();
 
         controller.value = controller.value.copyWith(
           selection: const TextSelection.collapsed(offset: 0),
         );
-        expect(controller.historyController.stack.length, 2);
+        expect(controller.historyController.stack.length, 1);
       });
 
       testWidgets('Limit depth', (WidgetTester wt) async {
```
Comment (alexeyinkin) [inline test/src/history/code_history_controller_test.dart:478]: Simplify, only test that bottom records are deleted.

File: lib/src/history/code_history_controller.dart [hunk 11]
```diff
@@ -46,41 +52,119 @@ class CodeHistoryController {
...
+        _setTimer();
+        break;
     }
 
-    if (!shouldSave) {
-      if (isTextChanging) {
-        _wasTextChanged = true;
-      }
+    lastCode = code;
+    lastSelection = selection;
```
Comment (alexeyinkin) [inline lib/src/history/code_history_controller.dart:88]: Move to the timer's case.

**Review by alexeyinkin — CHANGES_REQUESTED** [review]

File: test/src/history/code_history_controller_test.dart [hunk 12]
```diff
@@ -286,102 +277,101 @@ void main() {
...
-        await wt.sendRedo();
-        expect(controller.historyController.stack.length, 6);
-        expect(controller.code.text, code1.text);
-        expect(controller.selection, selection1);
-
-        await wt.sendRedo();
-        expect(controller.historyController.stack.length, 6);
-        expect(controller.code.text, code2.text);
-        expect(controller.selection, selection2);
+        for (int i = manualHistoryRecords.length - 2; i >= 0; i--) {
```
Comment (alexeyinkin) [inline test/src/history/code_history_controller_test.dart:334]:
```suggestion
        for (int i = manualHistoryRecords.length - 1; --i >= 0; ) {
```

File: test/src/history/code_history_controller_test.dart [hunk 13]
```diff
@@ -480,17 +469,22 @@ void main() {
...
-          controller.value = controller.value.typed('a');
-          await wt.moveCursor(-1); // Creates.
+
+        Code? firstCode;
+        TextSelection? firstSelection;
+
+        for (int i = 0; i < CodeHistoryController.limit - 2; i++) {
+          controller.value = controller.value.typed('ab'); // Creates.
+          firstCode ??= controller.code;
+          firstSelection ??= controller.selection;
```
Comment (alexeyinkin) [inline test/src/history/code_history_controller_test.dart:479]: codeAfterFirstEdit, selectionAfterFirstEdit
// Set after the first change.

**Review by alexeyinkin — CHANGES_REQUESTED** [review]

**Review by alexeyinkin — APPROVED** [review]
